spring.application.name=dad-needs-report

jwt.secret=f6799b2d8d056d7f61cf4ee4033fed0c28f81bb170788aa7c35d57bbc4fb94da
jwt.expiration=3

spring.datasource.url=jdbc:sqlite:./db/finances.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
